FROM microsoft/dotnet:2.1-runtime-alpine3.7

#############################################################
# my code below

RUN mkdir -p /root/src/app/docker-console
WORKDIR /root/src/app/docker-console

COPY ./app/alpine ./
ENTRYPOINT ["dotnet", "docker-console.dll"]
# CMD ["-c"]

RUN echo "finished docker build"